language: cpp
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - cmake
      - zlib1g-dev
      - libssl-dev
install:
  - mkdir deps
  - git clone https://github.com/uNetworking/uWebSockets deps/uWebSockets
  -   cd deps/uWebSockets
  -   make
  -   sudo make install
  -   cd ../..
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
